**Pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with structured (tabular, multidimensional, potentially heterogeneous) and time series data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.**

>> Pandas is designed to make it easier to work with structured data. Most of the analyses you might perform will likely involve using tabular data, e.g., from .csv files or relational databases (e.g., SQL). The DataFrame object in pandas is "a two-dimensional tabular, column-oriented data structure with both row and column labels."

**Here are just a few of the things that pandas does well:**

* Robust IO tools for loading data from flat files (CSV and delimited), Excel files, databases, and saving / loading data from the ultrafast HDF5 format

* Easy handling of missing data (represented as NaN) in floating point as well as non-floating point data

* size mutabiltiy: columns can be inserted and deleted from DataFrame and higher dimensional objects

* Automatic and explicit data alignment: objects can be explicitly aligned to a set of labels, or the user can simply ignore the labels and let Series, DataFrame, etc. automatically align the data for you in computations

* Powerful, flexible group by functionality to perform split-apply-combine operations on data sets, for both aggregating and transforming data

* Make it easy to convert ragged, differently-indexed data in other Python and NumPy data structures into DataFrame objects

* Intelligent label-based slicing, fancy indexing, and subsetting of large data sets
* Intuitive merging and joining data sets
* Flexible reshaping and pivoting of data sets
* Hierarchical labeling of axes (possible to have multiple labels per tick)

In [ ]:
# the data which is stored in rows and cols structured data

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

**Pandas DataFrames**

* In this chapter, you will learn about Pandas dataframes, a data structure in Python that provides the ability to work with tabular data. Pandas dataframes are composed of rows and columns that can have header names, and the columns in pandas dataframes can be different types (e.g. the first column containing integers and the second column containing text strings). Each value in pandas dataframe is referred to as a cell that has a specific row index and column index within the tabular structure.

In [3]:
# series : it is essentiallty a column
# DataFrame : A 2 D data scturcture, ie data  is allingend in tablular fasion of rows and colns
# pandas data frame : Series + series  = Dataframe

In [4]:
# first series
number_series  = pd.Series([1,2,3,4,5], name = "series of nums")
number_series

0    1
1    2
2    3
3    4
4    5
Name: series of nums, dtype: int64

In [5]:
# first series
number_series  = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'] , name = "series of nums")
number_series

a    1
b    2
c    3
d    4
e    5
Name: series of nums, dtype: int64

In [6]:
number_series['a']

1

In [7]:
number_series[0]

<ipython-input-7-6a2408185e6e>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  number_series[0]

1

In [8]:
# using 2 d array create dataframe
# creating our firstr dataframe

some_random_2darray = np.random.randint(4,6, size = (4,3))
some_random_2darray

array([[4, 4, 4],
       [5, 4, 4],
       [4, 5, 4],
       [4, 5, 4]])

In [9]:
first_dataframe = pd.DataFrame(some_random_2darray)
first_dataframe

   0  1  2
0  4  4  4
1  5  4  4
2  4  5  4
3  4  5  4

In [ ]:
first_dataframe = pd.DataFrame(some_random_2darray, columns = ['sam','karan','soumya'])
first_dataframe

   sam  karan  soumya
0    4      4       4
1    4      4       5
2    4      5       5
3    4      4       4

In [ ]:
first_dataframe = pd.DataFrame(some_random_2darray, index = ["Maths","Science","Python", "Geo"], columns = ['sam','karan','soumya'])
first_dataframe

         sam  karan  soumya
Maths      4      4       4
Science    4      4       5
Python     4      5       5
Geo        4      4       4

In [ ]:
# list of lists

list_of_lists = [['Amar',10],['Suhani',20],["Sam",21]]
list_of_lists

[['Amar', 10], ['Suhani', 20], ['Sam', 21]]

In [ ]:
df = pd.DataFrame(list_of_lists, columns=['Name','Age'])
df

# add index names also

     Name  Age
0    Amar   10
1  Suhani   20
2     Sam   21

In [ ]:
# using dict
employee_dict = {"Employee_Name":["Amar","Suhani","Sam"], "Income":[100000,200000,210000]}
employee_dict

{'Employee_Name': ['Amar', 'Suhani', 'Sam'],
 'Income': [100000, 200000, 210000]}

In [ ]:
df = pd.DataFrame(employee_dict)
df

  Employee_Name  Income
0          Amar  100000
1        Suhani  200000
2           Sam  210000

In [ ]:
# Store the data in a dictionary
series_dict = {'First Series' : pd.Series([10, 20, 30, 40]),
              'Second Series' : pd.Series([10, 20, 30, 40])}

df = pd.DataFrame(series_dict)
df

   First Series  Second Series
0            10             10
1            20             20
2            30             30
3            40             40

In [ ]:
list_of_dicts = [{'a': 1, 'b': 2, 'c':3}, {'a':10, 'b': 20, 'c': 30}]
df = pd.DataFrame(list_of_dicts)
df

    a   b   c
0   1   2   3
1  10  20  30

In [ ]:
# there are other ways

actor_names = ['Ryan Reynolds', 'Benedict Cumberbatch', 'Robert Downey Jr.', 'Chris Evans']
actor_ages = [48,52,54,np.nan]

list_of_tuples = list(zip(actor_names, actor_ages))
list_of_tuples

[('Ryan Reynolds', 48),
 ('Benedict Cumberbatch', 52),
 ('Robert Downey Jr.', 54),
 ('Chris Evans', nan)]

In [ ]:
actor_df = pd.DataFrame(list_of_tuples, columns = ['Name', 'Age'])
actor_df

                   Name   Age
0         Ryan Reynolds  48.0
1  Benedict Cumberbatch  52.0
2     Robert Downey Jr.  54.0
3           Chris Evans   NaN

In [ ]:
# methods and attributes avaailable with pandas

list(actor_df.index)

[0, 1, 2, 3]

In [ ]:
our_array = np.random.randn(100,5)

df = pd.DataFrame(our_array, columns=['a','b','c','d','e'])
df

           a         b         c         d         e
0   0.689732 -0.441533 -1.566720 -1.305102  1.488827
1   0.972996 -0.697384  0.936675 -0.905168 -1.244499
2   1.095078  0.816651 -1.047648  1.001697  0.913357
3  -0.343686  0.061762  0.281473 -0.512103  1.513370
4  -1.987919 -0.104541 -0.505185  0.726719 -0.636738
..       ...       ...       ...       ...       ...
95  0.145296  0.971073 -0.691603  0.793521 -0.415297
96 -1.059070 -0.004186 -0.040187 -0.405093  1.103875
97  0.296187  0.080375 -1.393169  1.051584  1.827699
98 -0.709627 -0.081541 -0.795437 -0.460072 -1.176079
99  1.111060  1.272185 -0.198456 -0.469920 -0.376288

[100 rows x 5 columns]

In [ ]:
# head()

df.head()

          a         b         c         d         e
0  0.689732 -0.441533 -1.566720 -1.305102  1.488827
1  0.972996 -0.697384  0.936675 -0.905168 -1.244499
2  1.095078  0.816651 -1.047648  1.001697  0.913357
3 -0.343686  0.061762  0.281473 -0.512103  1.513370
4 -1.987919 -0.104541 -0.505185  0.726719 -0.636738

In [ ]:
df.head(10) # we can also print first n rows

          a         b         c         d         e
0  0.689732 -0.441533 -1.566720 -1.305102  1.488827
1  0.972996 -0.697384  0.936675 -0.905168 -1.244499
2  1.095078  0.816651 -1.047648  1.001697  0.913357
3 -0.343686  0.061762  0.281473 -0.512103  1.513370
4 -1.987919 -0.104541 -0.505185  0.726719 -0.636738
5 -1.180202  2.514153 -0.773019  0.626093 -0.269101
6  0.582276  1.535292 -0.711452  1.569780 -0.912344
7  0.272911  0.819704 -1.423378 -2.546345 -0.281139
8  0.137165 -1.185896  1.848909  1.657037  1.640948
9 -0.301471 -1.423571 -0.962665  0.945914 -0.120877

In [ ]:
# columns
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
# info()
actor_df

                   Name   Age
0         Ryan Reynolds  48.0
1  Benedict Cumberbatch  52.0
2     Robert Downey Jr.  54.0
3           Chris Evans   NaN

In [ ]:
actor_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     3 non-null      float64
dtypes: float64(1), object(1)
memory usage: 192.0+ bytes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       100 non-null    float64
 1   b       100 non-null    float64
 2   c       100 non-null    float64
 3   d       100 non-null    float64
 4   e       100 non-null    float64
dtypes: float64(5)
memory usage: 4.0 KB

In [ ]:
# rename() easily yopu cn rename the colus
actor_df

                   Name   Age
0         Ryan Reynolds  48.0
1  Benedict Cumberbatch  52.0
2     Robert Downey Jr.  54.0
3           Chris Evans   NaN

In [ ]:
actor_df.rename(columns = {'Name':'Actor_Name', 'Age':'Actor_Age'},inplace=True)

In [ ]:
actor_df

             Actor_Name  Actor_Age
0         Ryan Reynolds       48.0
1  Benedict Cumberbatch       52.0
2     Robert Downey Jr.       54.0
3           Chris Evans        NaN

In [ ]:
actor_df = actor_df.rename({'Actor_Name':'Name'},axis=1)
actor_df

                   Name  Actor_Age
0         Ryan Reynolds       48.0
1  Benedict Cumberbatch       52.0
2     Robert Downey Jr.       54.0
3           Chris Evans        NaN

In [ ]:
actor_df

                   Name  Actor_Age
0         Ryan Reynolds       48.0
1  Benedict Cumberbatch       52.0
2     Robert Downey Jr.       54.0
3           Chris Evans        NaN

In [ ]:
df = pd.read_csv("/content/imdb_data.csv")

ParserError: Error tokenizing data. C error: EOF inside string starting at row 2890

In [ ]:
df.head()

          a         b         c         d         e
0  0.689732 -0.441533 -1.566720 -1.305102  1.488827
1  0.972996 -0.697384  0.936675 -0.905168 -1.244499
2  1.095078  0.816651 -1.047648  1.001697  0.913357
3 -0.343686  0.061762  0.281473 -0.512103  1.513370
4 -1.987919 -0.104541 -0.505185  0.726719 -0.636738

In [ ]:
df.shape

(100, 5)

In [ ]:
df_bigmart = pd.read_csv("/content/big_mart.csv")

In [ ]:
df_bigmart.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

**Up till now, we have been creating our own simple dataframes and exploring them. But of course life is not that simple. Most of the data you would deal with in your jobs would be a lot bigger and messier. Let us start with first loading these data in our Python environment.**

In [ ]:
# 80% od the work is of data prepration !
# machine leanirng
# deep leanirng 2 lines of code

In [ ]:
df_sentiment = pd.read_csv("https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/refs/heads/master/IMDB-Dataset.csv")

In [ ]:
df_sentiment.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df_new = pd.read_csv("https://raw.githubusercontent.com/LearnDataSci/articles/refs/heads/master/Python%20Pandas%20Tutorial%20A%20Complete%20Introduction%20for%20Beginners/IMDB-Movie-Data.csv")

In [ ]:
df_new.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
df_bigmart = pd.read_csv("/content/big_mart.csv")

In [ ]:
df_bigmart.head(20)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350
10,FDY07,11.800,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1,2187.1530
12,FDX32,15.100,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1,1589.2646
13,FDS46,17.600,Regular,0.047257,Snack Foods,119.6782,OUT046,1997,Small,Tier 1,Supermarket Type1,2145.2076
14,FDF32,16.350,Low Fat,0.068024,Fruits and Vegetables,196.4426,OUT013,1987,High,Tier 3,Supermarket Type1,1977.4260
15,FDP49,9.000,Regular,0.069089,Breakfast,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192
16,NCB42,11.800,Low Fat,0.008596,Health and Hygiene,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888
17,FDP49,9.000,Regular,0.069196,Breakfast,54.3614,OUT049,1999,Medium,Tier 1,Supermarket Type1,718.3982
18,DRI11,NaN,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
19,FDU02,13.350,Low Fat,0.102492,Dairy,230.5352,OUT035,2004,Small,Tier 2,Supermarket Type1,2748.4224

In [ ]:
df_bigmart.value_counts("Outlet_Size")

# 94 number !

Outlet_Size
Medium    2793
Small     2388
High       932
Name: count, dtype: int64

In [ ]:
df_bigmart.info()
# resources you have to be optimized
# gpu

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [ ]:
# where people prefer to go ? d mart ! dukan  6000 2000 , what if out of 8500 7500 null values hote? 2000

In [ ]:
#describe() method

df_bigmart.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [10]:
df = pd.read_csv("/content/imdb_data.csv")

In [11]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [12]:
df["crew"][0]

'[{\'credit_id\': \'59ac067c92514107af02c8c8\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1449071, \'job\': \'First Assistant Director\', \'name\': \'Kelly Cantley\', \'profile_path\': None}, {\'credit_id\': \'52fe4ee7c3a36847f82afad7\', \'department\': \'Directing\', \'gender\': 2, \'id\': 3227, \'job\': \'Director\', \'name\': \'Steve Pink\', \'profile_path\': \'/myHOgo8mQSCiCAZNGMRdHVr03jr.jpg\'}, {\'credit_id\': \'5524ed25c3a3687ded000d88\', \'department\': \'Writing\', \'gender\': 2, \'id\': 347335, \'job\': \'Writer\', \'name\': \'Josh Heald\', \'profile_path\': \'/pwXJIenrDMrG7t3zNfLvr8w1RGU.jpg\'}, {\'credit_id\': \'5524ed2d925141720c001128\', \'department\': \'Writing\', \'gender\': 2, \'id\': 347335, \'job\': \'Characters\', \'name\': \'Josh Heald\', \'profile_path\': \'/pwXJIenrDMrG7t3zNfLvr8w1RGU.jpg\'}, {\'credit_id\': \'5524ed3d92514166c1004a5d\', \'department\': \'Production\', \'gender\': 2, \'id\': 57822, \'job\': \'Producer\', \'name\': \'Andrew Panay\', \'profile_path\': None}, {\'credit_id\': \'5524ed4bc3a3687df3000dd2\', \'department\': \'Production\', \'gender\': 0, \'id\': 1451395, \'job\': \'Associate Producer\', \'name\': \'Adam Blum\', \'profile_path\': None}, {\'credit_id\': \'5524ed5a925141720c00112c\', \'department\': \'Production\', \'gender\': 2, \'id\': 52997, \'job\': \'Executive Producer\', \'name\': \'Rob Corddry\', \'profile_path\': \'/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg\'}, {\'credit_id\': \'5524ed85c3a3687e0e000f56\', \'department\': \'Production\', \'gender\': 0, \'id\': 62807, \'job\': \'Executive Producer\', \'name\': \'Ben Ormand\', \'profile_path\': None}, {\'credit_id\': \'5524ed9fc3a3687e0e000f59\', \'department\': \'Sound\', \'gender\': 2, \'id\': 23486, \'job\': \'Original Music Composer\', \'name\': \'Christophe Beck\', \'profile_path\': \'/2fnJUmCk6IEpVIptpYaUk31epHx.jpg\'}, {\'credit_id\': \'5524eda6c3a3687e03000d28\', \'department\': \'Camera\', \'gender\': 2, \'id\': 6117, \'job\': \'Director of Photography\', \'name\': \'Declan Quinn\', \'profile_path\': None}, {\'credit_id\': \'5524edb4925141720c00113d\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1451396, \'job\': \'Editor\', \'name\': \'Jamie Gross\', \'profile_path\': None}, {\'credit_id\': \'5524edc1925141727600102e\', \'department\': \'Production\', \'gender\': 0, \'id\': 22219, \'job\': \'Casting\', \'name\': \'Susie Farris\', \'profile_path\': None}, {\'credit_id\': \'5524edd192514171cb008257\', \'department\': \'Art\', \'gender\': 0, \'id\': 1002643, \'job\': \'Production Design\', \'name\': \'Ryan Berg\', \'profile_path\': None}, {\'credit_id\': \'555ad9be9251411e5b00d485\', \'department\': \'Production\', \'gender\': 2, \'id\': 57431, \'job\': \'Executive Producer\', \'name\': \'Matt Moore\', \'profile_path\': None}, {\'credit_id\': \'5677e93bc3a36816890087dc\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1551818, \'job\': \'Script Supervisor\', \'name\': \'Nicole Garcea\', \'profile_path\': None}, {\'credit_id\': \'5677e96a92514179e10093d0\', \'department\': \'Production\', \'gender\': 0, \'id\': 1551819, \'job\': \'Production Coordinator\', \'name\': \'Jason Salzman\', \'profile_path\': None}, {\'credit_id\': \'5677e98492514179d2008cd9\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1422996, \'job\': \'Costume Design\', \'name\': \'Carol Cutshall\', \'profile_path\': None}, {\'credit_id\': \'5677e9d5c3a368168e009414\', \'department\': \'Art\', \'gender\': 2, \'id\': 500199, \'job\': \'Set Decoration\', \'name\': \'Tim Cohn\', \'profile_path\': None}, {\'credit_id\': \'5677f89d9251417845001a61\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1527917, \'job\': \'Hair Department Head\', \'name\': \'Voni Hinkle\', \'profile_path\': None}, {\'credit_id\': \'5677f8b392514179dd0089fb\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1431554, \'job\': \'Makeup Department Head\', \'name\': \'Remi Savva\', \'profile_path\': None}, {\'credit_id\': \'5677f8d1c3a3681689008a4b\', \'department\': \'Art\', \'gender\': 0, \'id\': 66495, \'job\': \'Art Direction\', \'name\': \'Jason Baldwin Stewart\', \'profile_path\': None}, {\'credit_id\': \'5677f8eec3a3681685008dd5\', \'department\': \'Production\', \'gender\': 0, \'id\': 1412466, \'job\': \'Production Supervisor\', \'name\': \'Korey Budd\', \'profile_path\': None}, {\'credit_id\': \'5677f90a9251417845001a7d\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1401562, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary C. Bourgeois\', \'profile_path\': None}, {\'credit_id\': \'5677f91e9251417845001a84\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1396794, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gabriel J. Serrano\', \'profile_path\': None}, {\'credit_id\': \'5677f938c3a3681680008dd4\', \'department\': \'Editing\', \'gender\': 0, \'id\': 13168, \'job\': \'Dialogue Editor\', \'name\': \'Victoria Rose Sampson\', \'profile_path\': None}, {\'credit_id\': \'5677f94e92514179dd008a1f\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1551839, \'job\': \'Production Sound Mixer\', \'name\': \'Michael B. Koff\', \'profile_path\': None}, {\'credit_id\': \'5677f968c3a368168e009698\', \'department\': \'Sound\', \'gender\': 0, \'id\': 113052, \'job\': \'Sound Effects Editor\', \'name\': \'Randall Guth\', \'profile_path\': None}, {\'credit_id\': \'5677f98dc3a3681685008e02\', \'department\': \'Crew\', \'gender\': 2, \'id\': 1442535, \'job\': \'Stunt Coordinator\', \'name\': \'Chuck Picerni Jr.\', \'profile_path\': \'/yE5QtXUzcrnCzMRctZL8F5g842B.jpg\'}, {\'credit_id\': \'5677f9a692514179dd008a49\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1437305, \'job\': \'Camera Operator\', \'name\': \'Michael Applebaum\', \'profile_path\': None}, {\'credit_id\': \'5677f9bd9251417845001aae\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1401765, \'job\': \'Still Photographer\', \'name\': \'Steve Dietl\', \'profile_path\': None}, {\'credit_id\': \'5677f9e592514179e7008bf7\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1402721, \'job\': \'Rigging Gaffer\', \'name\': \'Tarik Naim Alherimi\', \'profile_path\': None}, {\'credit_id\': \'5677f9f4c3a368167c0090ed\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1402719, \'job\': \'Gaffer\', \'name\': \'Paul Olinde\', \'profile_path\': None}, {\'credit_id\': \'5677fa21c3a368168e0096ca\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1551840, \'job\': \'Music Supervisor\', \'name\': \'Steve Griffen\', \'profile_path\': None}, {\'credit_id\': \'5677fa31c3a3681680008e04\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1551841, \'job\': \'Music Editor\', \'name\': \'Matt Fausak\', \'profile_path\': None}, {\'credit_id\': \'5677fa4392514179dd008a76\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1551840, \'job\': \'Music Editor\', \'name\': \'Steve Griffen\', \'profile_path\': None}, {\'credit_id\': \'5677fa609251417845001acf\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1403416, \'job\': \'Costume Supervisor\', \'name\': \'Shonta T. McCray\', \'profile_path\': None}, {\'credit_id\': \'5677fa8492514179d2008fb3\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1425831, \'job\': \'Steadicam Operator\', \'name\': \'Mark Karavite\', \'profile_path\': None}, {\'credit_id\': \'5677fab2c3a3681689008ac3\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1551842, \'job\': \'First Assistant Camera\', \'name\': \'Joe Waistell\', \'profile_path\': None}, {\'credit_id\': \'5677faecc3a368168e0096fe\', \'department\': \'Sound\', \'gender\': 0, \'id\': 58362, \'job\': \'Supervising Sound Editor\', \'name\': \'Michael Hilkene\', \'profile_path\': None}, {\'credit_id\': \'59ac0368c3a3682c0a02c484\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1881584, \'job\': \'Additional Writing\', \'name\': \'John Karnay\', \'profile_path\': None}, {\'credit_id\': \'59ac0411c3a3682bf0028966\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1431552, \'job\': \'Hairstylist\', \'name\': \'Daina Daigle\', \'profile_path\': None}, {\'credit_id\': \'59ac0504925141072302b8fb\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1712001, \'job\': \'Makeup Artist\', \'name\': \'Allison Gordin\', \'profile_path\': None}, {\'credit_id\': \'59ac0570c3a3682bf0028aac\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 578725, \'job\': \'Makeup Artist\', \'name\': \'Darryl Lucas\', \'profile_path\': None}, {\'credit_id\': \'59ac05a4925141077e02c97e\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1463274, \'job\': \'Makeup Artist\', \'name\': \'Annabelle MacNeal\', \'profile_path\': None}, {\'credit_id\': \'59ac05c6925141076502d106\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1881586, \'job\': \'Makeup Artist\', \'name\': \'Marina Savva\', \'profile_path\': None}, {\'credit_id\': \'59ac0615c3a3682c480296aa\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1406267, \'job\': \'Hairstylist\', \'name\': \'Carl G. Variste\', \'profile_path\': None}, {\'credit_id\': \'59ac06ba925141076502d1fa\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1798593, \'job\': \'First Assistant Director\', \'name\': \'Josh King\', \'profile_path\': None}, {\'credit_id\': \'59ac06f1c3a3682c2202aca0\', \'department\': \'Art\', \'gender\': 0, \'id\': 1415083, \'job\': \'Greensman\', \'name\': \'Scott C. Bivona\', \'profile_path\': None}, {\'credit_id\': \'59ac072c925141076502d260\', \'department\': \'Art\', \'gender\': 0, \'id\': 1881587, \'job\': \'Title Designer\', \'name\': \'Eunha Choi\', \'profile_path\': None}, {\'credit_id\': \'59ac077c925141077e02cb62\', \'department\': \'Art\', \'gender\': 0, \'id\': 1585302, \'job\': \'Construction Coordinator\', \'name\': \'Daniel Coe\', \'profile_path\': None}, {\'credit_id\': \'59ac07e0925141078a02d842\', \'department\': \'Art\', \'gender\': 0, \'id\': 1495523, \'job\': \'Set Designer\', \'name\': \'Spencer Davison\', \'profile_path\': None}, {\'credit_id\': \'59ac0862925141072f02cf6f\', \'department\': \'Art\', \'gender\': 0, \'id\': 1881589, \'job\': \'Painter\', \'name\': \'Sonia L. Garcia\', \'profile_path\': None}, {\'credit_id\': \'59ac08e0c3a3682bf0028e51\', \'department\': \'Art\', \'gender\': 0, \'id\': 1424896, \'job\': \'Art Department Coordinator\', \'name\': \'Caleb Guillotte\', \'profile_path\': None}, {\'credit_id\': \'59ac0920c3a3682c2202af36\', \'department\': \'Art\', \'gender\': 0, \'id\': 1393375, \'job\': \'Leadman\', \'name\': "Pat A. O\'Connor", \'profile_path\': None}, {\'credit_id\': \'59ac095592514107af02cc39\', \'department\': \'Art\', \'gender\': 0, \'id\': 1881592, \'job\': \'Set Designer\', \'name\': \'Brendan Turrill\', \'profile_path\': None}, {\'credit_id\': \'59ac0989925141072302bdfa\', \'department\': \'Art\', \'gender\': 2, \'id\': 76497, \'job\': \'Property Master\', \'name\': \'Brook Yeaton\', \'profile_path\': None}, {\'credit_id\': \'59ac0a2cc3a3682c9c02add1\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1881596, \'job\': \'Boom Operator\', \'name\': \'Matthew Armstrong\', \'profile_path\': None}, {\'credit_id\': \'59ac0aa8925141072f02d282\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 1558086, \'job\': \'Special Effects Supervisor\', \'name\': \'Matt Kutcher\', \'profile_path\': None}, {\'credit_id\': \'59ac0b2ac3a3682c2202b192\', \'department\': \'Crew\', \'gender\': 2, \'id\': 1558087, \'job\': \'Special Effects Coordinator\', \'name\': \'Eric Roberts\', \'profile_path\': None}, {\'credit_id\': \'59ac0b7ac3a3682c2202b1fb\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1392098, \'job\': \'Visual Effects Supervisor\', \'name\': \'Rocco Passionino\', \'profile_path\': None}, {\'credit_id\': \'59ac0bbe925141077e02d0c4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1558716, \'job\': \'Visual Effects Coordinator\', \'name\': \'Joseph Payo\', \'profile_path\': None}, {\'credit_id\': \'59ac0bf2c3a3682cc802cefa\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1408784, \'job\': \'Visual Effects Producer\', \'name\': \'Chris Roff\', \'profile_path\': None}, {\'credit_id\': \'59ac0c51c3a3682c48029d99\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1881600, \'job\': \'Best Boy Electric\', \'name\': \'Ulyan Atamanyuk\', \'profile_path\': None}, {\'credit_id\': \'59ac0cbac3a3682c0a02cff6\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1881602, \'job\': \'Key Grip\', \'name\': \'Chris Ekstrom\', \'profile_path\': None}, {\'credit_id\': \'59ac0d54925141072f02d5e6\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1484984, \'job\': \'Best Boy Electric\', \'name\': \'Brad Garris\', \'profile_path\': None}, {\'credit_id\': \'59ac0db0925141078a02df86\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1881603, \'job\': \'Dolly Grip\', \'name\': \'Kendell Joseph\', \'profile_path\': None}, {\'credit_id\': \'59ac0e5a925141077e02d39f\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1549179, \'job\': \'Dolly Grip\', \'name\': \'Spencer Wilcox\', \'profile_path\': None}, {\'credit_id\': \'59ac0e9f925141079d02bee6\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1552626, \'job\': \'Key Costumer\', \'name\': \'Sarah P. Koeppe\', \'profile_path\': None}, {\'credit_id\': \'59ac0ec1c3a3682bf0029524\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1881605, \'job\': \'Seamstress\', \'name\': \'Catherine Rodi\', \'profile_path\': None}, {\'credit_id\': \'59ac0eef925141070702c7ff\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1463801, \'job\': \'Seamstress\', \'name\': \'Giselle Spence\', \'profile_path\': None}, {\'credit_id\': \'59ac0f5dc3a3682c4802a0f5\', \'department\': \'Production\', \'gender\': 0, \'id\': 1400837, \'job\': \'Location Manager\', \'name\': \'John A. Johnston\', \'profile_path\': None}, {\'credit_id\': \'59ac0ff2c3a3682c4802a196\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1844322, \'job\': \'Production Controller\', \'name\': \'Gail Marks\', \'profile_path\': None}]'

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

**Indexing and Slicing**
>> loc and iloc methods

**iloc gets rows (or columns) at particular positions in the index (so it only takes integers).**
1. The iloc() function is an indexed-based selecting method which means that we have to pass an integer index in the method to select a specific row/column.
**loc is label based data selecting method, you need to pass the name of row or the coumn that you want to work with**

In [14]:
# importing the module
import pandas as pd

# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
                               'Mahindra', 'Maruti', 'Hyundai',
                               'Renault', 'Tata', 'Maruti'],
                     'Year': [2012, 2014, 2011, 2015, 2012,
                              2016, 2014, 2018, 2019],
                     'Kms Driven': [50000, 30000, 60000,
                                    25000, 10000, 46000,
                                    31000, 15000, 12000],
                     'City': ['Gurgaon', 'Delhi', 'Mumbai',
                              'Delhi', 'Mumbai', 'Delhi',
                              'Mumbai', 'Chennai',  'Ghaziabad'],
                     'Mileage':  [28, 27, 25, 26, 28,
                                  29, 24, 21, 24]})

# displaying the DataFrame
display(data)

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [15]:
# selct the cars which have the brand maruti and milage > 25
# selecting cars with brand 'Maruti' and Mileage > 25
display(data.loc[(data.Brand == 'Maruti') & (data.Mileage > 25)])

    Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [16]:
# Example 2: Selecting a Range of Rows From the DataFrame
display(data.loc[2: 5])

      Brand  Year  Kms Driven    City  Mileage
2      Tata  2011       60000  Mumbai       25
3  Mahindra  2015       25000   Delhi       26
4    Maruti  2012       10000  Mumbai       28
5   Hyundai  2016       46000   Delhi       29

In [17]:

# updating values of Mileage if Year < 2015
data.loc[(data.Year < 2015), ['Mileage']] = 22
display(data)

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       22
1   Hyundai  2014       30000      Delhi       22
2      Tata  2011       60000     Mumbai       22
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       22
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       22
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [18]:

# selecting 0th, 2nd, 4th, and 7th index rows
display(data.iloc[[0, 2, 4, 7]])

    Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       22
2    Tata  2011       60000   Mumbai       22
4  Maruti  2012       10000   Mumbai       22
7    Tata  2018       15000  Chennai       21

In [19]:
data.iloc[1:10, 2:5]

   Kms Driven       City  Mileage
1       30000      Delhi       22
2       60000     Mumbai       22
3       25000      Delhi       26
4       10000     Mumbai       22
5       46000      Delhi       29
6       31000     Mumbai       22
7       15000    Chennai       21
8       12000  Ghaziabad       24

In [20]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [21]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [22]:
df.iloc[:, -3:]

,cast,crew,revenue
0,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
...,...,...,...
2995,"[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,"[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,"[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,"[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,"[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [23]:
# loc gets rows (or columns) with particular labels from the index.
df.loc[50:60, ['budget','genres','runtime']]

       budget                                             genres  runtime
50     560000  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...    102.0
51   12000000  [{'id': 12, 'name': 'Adventure'}, {'id': 35, '...    160.0
52          0  [{'id': 12, 'name': 'Adventure'}, {'id': 10751...     97.0
53          0  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...     98.0
54   20000000                     [{'id': 28, 'name': 'Action'}]    107.0
55          0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...     95.0
56          0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...     97.0
57  125000000  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...    125.0
58          0  [{'id': 10402, 'name': 'Music'}, {'id': 10749,...     95.0
59   14000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...     95.0
60  150000000  [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...    144.0

In [24]:
new_df = df[['original_language','release_date','cast']]

In [25]:
new_df.head()

,original_language,release_date,cast
0,en,2/20/15,"[{'cast_id': 4, 'character': 'Lou', 'credit_id..."
1,en,8/6/04,"[{'cast_id': 1, 'character': 'Mia Thermopolis'..."
2,en,10/10/14,"[{'cast_id': 5, 'character': 'Andrew Neimann',..."
3,hi,3/9/12,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '..."
4,ko,2/5/09,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred..."

In [26]:
# in pandas we can perform boolean indexing

df["original_language"] == "en"

0        True
1        True
2        True
3       False
4       False
        ...
2995     True
2996    False
2997     True
2998     True
2999     True
Name: original_language, Length: 3000, dtype: bool

In [27]:
english_movies = df[df["original_language"] == "en"]
english_movies

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,9/18/92,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just because you’re accepted doesn’t mean you ...,School Ties,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [28]:
non_english_movies = df[df['original_language'] != 'en']
non_english_movies.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
15,16,NaN,500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://skinningmovie.com/synopsis.htm,tt1129437,sr,Šišanje,Novica is a mathematics champion in a Belgrade...,1.018477,...,10/6/10,97.0,"[{'iso_639_1': 'sr', 'name': 'Srpski'}]",Released,Life is sometimes rude game: one mistake can b...,Skinning,"[{'id': 379, 'name': 'skinhead'}, {'id': 7492,...","[{'cast_id': 1001, 'character': 'Novica', 'cre...","[{'credit_id': '52fe4927c3a36847f818bb5f', 'de...",198
30,31,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1675434,fr,Intouchables,A true story of two men who should never have ...,16.086919,...,11/2/11,112.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sometimes you have to reach into someone else'...,The Intouchables,"[{'id': 3230, 'name': 'male friendship'}, {'id...","[{'cast_id': 6, 'character': 'Philippe', 'cred...","[{'credit_id': '52fe4967c3a368484e129b63', 'de...",426480871
31,32,NaN,0,"[{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...",http://www.cache-derfilm.at,tt0387898,fr,Caché,A married couple is terrorized by a series of ...,5.695860,...,5/2/05,117.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Caché,"[{'id': 90, 'name': 'paris'}, {'id': 213, 'nam...","[{'cast_id': 2, 'character': 'Georges Laurent'...","[{'credit_id': '52fe4244c3a36847f8011073', 'de...",36000000

In [29]:
long_movies = df[df['runtime'] >= 120]
long_movies[["title","cast"]]

,title,cast
3,Kahaani,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '..."
12,American Beauty,"[{'cast_id': 6, 'character': 'Lester Burnham',..."
14,Minority Report,"[{'cast_id': 5, 'character': 'Chief John Ander..."
20,Lost in Space,"[{'cast_id': 26, 'character': 'Dr. Zachary Smi..."
33,ABCs of Death 2,"[{'cast_id': 60, 'character': 'Assassin (Segme..."
...,...,...
2970,The Bodyguard,"[{'cast_id': 17, 'character': 'Rachel Marron',..."
2980,Action Hero Biju,"[{'cast_id': 1, 'character': 'Sub-Inspector Bi..."
2992,The Thief of Bagdad,"[{'cast_id': 3, 'character': 'The Thief of Bag..."
2993,The Terminal,"[{'cast_id': 4, 'character': 'Viktor Navorski'..."
2997,The Long Kiss Goodnight,"[{'cast_id': 10, 'character': 'Samantha Caine ..."

In [30]:
# print all the en movies having runtime > 120

(df['original_language'] == 'en') & (df['runtime'] >120)

0       False
1       False
2       False
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Length: 3000, dtype: bool

In [31]:
long_english_movies = df[(df['original_language'] == 'en') & (df['runtime'] >120)]
long_english_movies

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
12,13,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",20.726578,...,9/15/99,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Look closer.,American Beauty,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 6, 'character': 'Lester Burnham',...","[{'credit_id': '52fe420ec3a36847f80007c5', 'de...",356296601
14,15,NaN,102000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0181689,en,Minority Report,John Anderton is a top 'Precrime' cop in the l...,20.666063,...,6/20/02,145.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The system is perfect until it comes after you.,Minority Report,"[{'id': 476, 'name': 'self-fulfilling prophecy...","[{'cast_id': 5, 'character': 'Chief John Ander...","[{'credit_id': '52fe4223c3a36847f8006f3d', 'de...",358372926
20,21,NaN,80000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,tt0120738,en,Lost in Space,The prospects for continuing life on Earth in ...,12.000579,...,4/3/98,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Danger, Will Robinson!",Lost in Space,"[{'id': 4379, 'name': 'time travel'}, {'id': 1...","[{'cast_id': 26, 'character': 'Dr. Zachary Smi...","[{'credit_id': '52fe433bc3a36847f80448b9', 'de...",136159423
33,34,"[{'id': 207632, 'name': 'The ABCs of Death Col...",0,"[{'id': 27, 'name': 'Horror'}]",NaN,tt2926810,en,ABCs of Death 2,Taking all that was great from the first insta...,8.254856,...,10/2/14,125.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Some people never learn,ABCs of Death 2,"[{'id': 9706, 'name': 'anthology'}, {'id': 187...","[{'cast_id': 60, 'character': 'Assassin (Segme...","[{'credit_id': '52fe4cd69251416c91101d73', 'de...",7171
37,38,NaN,50000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0114069,en,Outbreak,A deadly airborne virus finds its way into the...,13.676444,...,3/10/95,127.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,This animal carries a deadly virus... and the ...,Outbreak,"[{'id': 1261, 'name': 'river'}, {'id': 1402, '...","[{'cast_id': 1, 'character': 'Sam Daniels', 'c...","[{'credit_id': '52fe446ac3a36847f80949d3', 'de...",189859560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2967,2968,"[{'id': 387219, 'name': 'The Hustler Collectio...",2000000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0054997,en,The Hustler,Fast Eddie Felson is a small-time pool hustler...,9.333533,...,9/25/61,134.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They called him Fast Eddie. He was a winner. H...,The Hustler,"[{'id': 236, 'name': 'suicide'}, {'id': 395, '...","[{'cast_id': 15, 'character': 'Eddie Felson', ...","[{'credit_id': '52fe4297c3a36847f802a989', 'de...",7600000
2969,2970,NaN,19800000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,tt0280707,en,Gosford Park,"Multiple storylined drama set in 1932, showing...",14.101101,...,11/7/01,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Tea at four. Dinner at eight. Murder at midnight.,Gosford Park,"[{'id': 964, 'name': 'servant'}, {'id': 10594,...","[{'cast_id': 2, 'character': 'Mrs. Wilson', 'c...","[{'credit_id': '52fe4401c3a36847f807ceab', 'de...",87754044
2970,2971,NaN,25000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",NaN,tt0103855,en,The Bodyguard,A former Secret Service agent grudgingly takes...,9.805017,...,11/25/92,129.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Never let her out of your sight. Never let you...,The Bodyguard,"[{'id': 1156, 'name': 'sister sister relations...","[{'cast_id': 17, 'character': 'Rachel Marron',...","[{'credit_id': '52fe425ec3a36847f8019133', 'de...",411006740
2992,2993,NaN,1135654,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0015400,en,The Thief of Bagdad,A recalcitrant thief vies with a duplicitous M...,3.878515,...,3/18/24,149.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,"""Happiness Must Be Earned""",The Thief of Bagdad,"[{'id': 255, 'name': 'male nudity'}, {'id': 14...","[{'cast_id': 3, 'character': 'The Thief of Bag...","[{'credit_id': '52fe45bec3a368484e06c70b', 'de...",1213880
2993,2994,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,Viktor Navorski is a man without a country; hi...,14.092373,...,6/17/04,128.0,"[{'iso_639_1': 'bg', 'name': 'български език'}...",Released,Life is waiting.,The Terminal,"[{'id': 242, 'name': 'new york'}, {'id': 822, ...","[{'cast_id': 4, 'character': 'Viktor Navorski'...","[{'credit_id': '52fe4259c3a36847f8017699', 'de...",219417255

In [32]:
# how can we manipulate the columns
df['runtime']

0        93.0
1       113.0
2       105.0
3       122.0
4       118.0
        ...
2995    102.0
2996    102.0
2997    120.0
2998     90.0
2999    106.0
Name: runtime, Length: 3000, dtype: float64

In [33]:
df['new_runtime'] = df['runtime'] * 0.5

In [34]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,new_runtime
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0

In [35]:
df["movie_profit"] = df["revenue"] - df["budget"]

In [36]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,new_runtime,movie_profit
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,-1685349
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,55149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,9792000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,14800000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,3923970

In [37]:
# drop the columns
df.drop(columns = ['id'], axis = 1,inplace=True)

In [38]:
df.head()

,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,new_runtime,movie_profit
0,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,/tQtWuwvMf0hCc2QR2tkolwl7c3c.jpg,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,-1685349
1,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,/w9Z7A0GHEhIp7etpj0vyKOeU1Wx.jpg,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,55149435
2,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,9792000
3,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,/aTXRaPrWSinhcmCrcfJK17urp3F.jpg,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,14800000
4,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,/m22s7zvkVFDU9ir56PiiqIEWFdT.jpg,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,3923970

In [39]:
df.drop(["new_runtime", "poster_path"],axis = 1, inplace=True)

In [40]:
df.head()

,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,movie_profit
0,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349
1,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]",...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435
2,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...",...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000
3,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000
4,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,NaN,...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970

In [41]:
# perfom all the basic operation
df["budget"].sum()

67594002330

In [42]:
df["budget"].mean()

22531334.11

In [43]:
df.set_index("imdb_id", inplace=True)

In [44]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,movie_profit
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349
tt0368933,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435
tt2582802,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000
tt1821480,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,"[{'iso_3166_1': 'IN', 'name': 'India'}]",...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000
tt1380152,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,NaN,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970

In [45]:
df["budget"][1:5].sum()

44500000

In [46]:
# apply() to every col

# conver col to uppercase()
def to_uppercase(column):
  return column.upper()

In [47]:
df["capitalized_title"] = df["title"].apply(to_uppercase)

In [48]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,movie_profit,capitalized_title
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,HOT TUB TIME MACHINE 2
tt0368933,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT
tt2582802,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,WHIPLASH
tt1821480,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,"[{'iso_3166_1': 'IN', 'name': 'India'}]",...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,KAHAANI
tt1380152,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,NaN,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,MARINE BOY

In [49]:
def add_two_numbers(a,b):
  return a+b

In [50]:
x = lambda a,b : a+b
x(1,5)

6

In [51]:
add_two_numbers(1,2)

3

In [52]:
def revised_profit(revenue, budget):
  if revenue>0:
    new_profit = revenue - budget
  else:
    new_profit = np.nan

  return new_profit

In [53]:
df["new_profit"] = df.apply(lambda x : revised_profit(x["revenue"], x["budget"]), axis = 1)

In [54]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,status,tagline,title,Keywords,cast,crew,revenue,movie_profit,capitalized_title,new_profit
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,HOT TUB TIME MACHINE 2,-1685349
tt0368933,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,55149435
tt2582802,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,WHIPLASH,9792000
tt1821480,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,"[{'iso_3166_1': 'IN', 'name': 'India'}]",...,Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,KAHAANI,14800000
tt1380152,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,NaN,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",...,Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,MARINE BOY,3923970

In [55]:
# we can sort the dataframes in acending and decending order
df.sort_values("new_profit", ascending=False)

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,status,tagline,title,Keywords,cast,crew,revenue,movie_profit,capitalized_title,new_profit
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2820852,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'JP', 'name': 'Japan'}, {'iso_...",...,Released,Vengeance Hits Home,Furious 7,"[{'id': 830, 'name': 'car race'}, {'id': 3428,...","[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,1316249360,FURIOUS 7,1316249360
tt0848228,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Some assembly required.,The Avengers,"[{'id': 242, 'name': 'new york'}, {'id': 5539,...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,1299557910,THE AVENGERS,1299557910
tt2395427,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,"[{'name': 'Marvel Studios', 'id': 420}, {'name...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,A New Age Has Come.,Avengers: Age of Ultron,"[{'id': 8828, 'name': 'marvel comic'}, {'id': ...","[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694,1125403694,AVENGERS: AGE OF ULTRON,1125403694
tt2771200,NaN,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,287.253654,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",...,Released,Be our guest.,Beauty and the Beast,"[{'id': 254, 'name': 'france'}, {'id': 2343, '...","[{'cast_id': 174, 'character': 'Belle', 'credi...","[{'credit_id': '551879bec3a3681f840004eb', 'de...",1262886337,1102886337,BEAUTY AND THE BEAST,1102886337
tt1399103,"[{'id': 8650, 'name': 'Transformers Collection...",195000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.transformersmovie.com/,en,Transformers: Dark of the Moon,Sam Witwicky takes his first tenuous steps int...,4.503505,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,The invasion we always feared. An enemy we nev...,Transformers: Dark of the Moon,"[{'id': 305, 'name': 'moon'}, {'id': 1612, 'na...","[{'cast_id': 3, 'character': 'Sam Witwicky', '...","[{'credit_id': '537f0b740e0a2624b40044d0', 'de...",1123746996,928746996,TRANSFORMERS: DARK OF THE MOON,928746996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tt0455824,NaN,130000000,"[{'id': 18, 'name': 'Drama'}]",NaN,en,Australia,"Set in northern Australia before World War II,...",9.566135,"[{'name': 'Bazmark Films', 'id': 240}, {'name'...","[{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...",...,Released,Welcome to Australia!,Australia,"[{'id': 440, 'name': 'missionary'}, {'id': 195...","[{'cast_id': 3, 'character': 'Lady Sarah Ashle...","[{'credit_id': '52fe446cc3a36847f809546f', 'de...",49554002,-80445998,AUSTRALIA,-80445998
tt2361317,NaN,108000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",http://www.livebynight.movie/,en,Live by Night,A story set in the Prohibition Era and centere...,19.943930,"[{'name': 'Appian Way', 'id': 562}, {'name': '...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Witness the price of the American Dream.,Live by Night,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 0, 'character': 'Joe Coughlin', '...","[{'credit_id': '5327f970c3a3683179001eb4', 'de...",22678555,-85321445,LIVE BY NIGHT,-85321445
tt0112760,NaN,98000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,en,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",7.284477,"[{'name': 'Le Studio Canal+', 'id': 183}, {'na...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",...,Released,The Course Has Been Set. There Is No Turning B...,Cutthroat Island,"[{'id': 911, 'name': 'exotic island'}, {'id': ...","[{'cast_id': 1, 'character': 'Morgan Adams', '...","[{'credit_id': '52fe42f4c3a36847f802f69f', 'de...",10017322,-87982678,CUTTHROAT ISLAND,-87982678
tt0180052,NaN,100000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,en,The Adventures of Pluto Nash,"The year is 2087, the setting is the moon. Plu...",8.903754,"[{'name': 'Village Roadshow Pictures', 'id': 7...","[{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...",...,Released,Action's future has arrived...,The Adventures of Pluto Nash,"[{'id': 305, 'name': 'moon'}, {'id': 585, 'nam...","[{'cast_id': 10, 'character': 'Pluto Nash', 'c...","[{'credit_id': '52fe447a9251416c750362df', 'de...",7103973,-92896027,THE ADVENTURES OF PLUTO NASH,-92896027
tt2239822,NaN,197471676,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",NaN,en,Valerian and the City of a Thousand Planets,"In the 28th century, Valerian and Laureline ar...",15.262706,"[{'name': 'EuropaCorp', 'id': 6896}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",...,Released,NaN,Valerian and the City of a Thousand Planets,"[{'id': 1370, 'name': 'shapeshifting'}, {'id':...",NaN,NaN,90024292,-107447384,VALERIAN AND THE CITY OF A THOUSAND PLANETS,-107447384

In [56]:
# sort multiple colum
df.sort_values(['status','new_profit'], ascending=[False,True]).head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,status,tagline,title,Keywords,cast,crew,revenue,movie_profit,capitalized_title,new_profit
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt0145394,NaN,891000,"[{'id': 99, 'name': 'Documentary'}]",NaN,en,A Place Called Chiapas,"On January 1, 1994, the Zapatista National Lib...",0.179246,NaN,"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",...,Rumored,Inside the world's first postmodern revolution,A Place Called Chiapas,"[{'id': 187056, 'name': 'woman director'}]","[{'cast_id': 1, 'character': 'Himself', 'credi...","[{'credit_id': '57b4f7619251417287000dfc', 'de...",229000,-662000,A PLACE CALLED CHIAPAS,-662000
tt1860180,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,en,Billy Gardell: Halftime,"Billy Gardell, the star of CBS' hit comedy ""Mi...",0.007877,NaN,"[{'iso_3166_1': 'US', 'name': 'United States o...",...,Rumored,NaN,Billy Gardell: Halftime,NaN,"[{'cast_id': 9, 'character': 'Himself', 'credi...","[{'credit_id': '52fe4be1c3a368484e19d265', 'de...",60,60,BILLY GARDELL: HALFTIME,60
tt0120254,"[{'id': 144200, 'name': 'Swan Princess Series'...",0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 16, 'na...",NaN,en,The Swan Princess: Escape from Castle Mountain,The first wedding anniversary of Princess Odet...,5.121309,NaN,NaN,...,Rumored,It Will Take All Her Magic to Rescue Her Friends!,The Swan Princess: Escape from Castle Mountain,"[{'id': 3071, 'name': 'prince'}, {'id': 4456, ...","[{'cast_id': 2, 'character': 'Odette (voice)',...","[{'credit_id': '52fe488bc3a36847f816cfd3', 'de...",273644,273644,THE SWAN PRINCESS: ESCAPE FROM CASTLE MOUNTAIN,273644
tt0091024,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,en,Extremities,A woman escapes from the man who is about to r...,10.273979,"[{'name': 'Atlantic Entertainment Group', 'id'...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Rumored,"When fear made her a victim, she turned fear i...",Extremities,"[{'id': 2483, 'name': 'nudity'}, {'id': 2539, ...","[{'cast_id': 1, 'character': 'Marjorie', 'cred...","[{'credit_id': '582cca1c925141780b00259f', 'de...",13418091,13418091,EXTREMITIES,13418091
tt2239822,NaN,197471676,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",NaN,en,Valerian and the City of a Thousand Planets,"In the 28th century, Valerian and Laureline ar...",15.262706,"[{'name': 'EuropaCorp', 'id': 6896}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",...,Released,NaN,Valerian and the City of a Thousand Planets,"[{'id': 1370, 'name': 'shapeshifting'}, {'id':...",NaN,NaN,90024292,-107447384,VALERIAN AND THE CITY OF A THOUSAND PLANETS,-107447384

**Let us explore some datetime operations and functions**

* %a Weekday as locale’s abbreviated name. Sun, Mon, …, Sat (en_US)So, Mo, …, Sa (de_DE)
* %A Weekday as locale’s full name. Sunday, Monday, …, Saturday (en_US)Sonntag, Montag, …, Samstag (de_DE)
* %w Weekday as a decimal number, where 0 is Sunday and 6 is Saturday. 0, 1, 2, 3, 4, 5, 6
* %d Day of the month as a zero-padded decimal number. 01, 02, …, 31
* %b Month as locale’s abbreviated name. Jan, Feb, …, Dec (en_US)Jan, Feb, …, Dez (de_DE)
*%B Month as locale’s full name. January, February, …, December (en_US)Januar, Februar, …, Dezember (de_DE)
* %m Month as a zero-padded decimal number. 01, 02 … 12
*%y Year without century as a zero-padded decimal number. 01, 02, … 99
* %Y Year with century as a decimal number. 0001, 0002, … , 9999
* %H Hour (24-hour clock) as a zero-padded decimal number. 01, 02, … , 23
* %I Hour (12-hour clock) as a zero-padded decimal number. 01, 02, … , 12
* %p Locale’s equivalent of either AM or PM. AM, PM (en_US)
* %M Minute as a zero-padded decimal number. 01, 02, … , 59
* %S Second as a zero-padded decimal number. 01, 02, … , 59
* %f Microsecond as a decimal number, zero-padded on the left. 000000, 000001, …, 999999

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3000 entries, tt2637294 to tt1600195
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  604 non-null    object
 1   budget                 3000 non-null   int64
 2   genres                 2993 non-null   object
 3   homepage               946 non-null    object
 4   original_language      3000 non-null   object
 5   original_title         3000 non-null   object
 6   overview               2992 non-null   object
 7   popularity             3000 non-null   float64
 8   production_companies   2844 non-null   object
 9   production_countries   2945 non-null   object
 10  release_date           3000 non-null   object
 11  runtime                2998 non-null   float64
 12  spoken_languages       2980 non-null   object
 13  status                 3000 non-null   object
 14  tagline                2403 non-null   object
 15  title                  3000 non-null   object
 16  Keywords               2724 non-null   object
 17  cast                   2987 non-null   object
 18  crew                   2984 non-null   object
 19  revenue                3000 non-null   int64
 20  movie_profit           3000 non-null   int64
 21  capitalized_title      3000 non-null   object
 22  new_profit             3000 non-null   int64
dtypes: float64(2), int64(4), object(17)
memory usage: 562.5+ KB

In [60]:
df['release_date']

imdb_id
tt2637294     2/20/15
tt0368933      8/6/04
tt2582802    10/10/14
tt1821480      3/9/12
tt1380152      2/5/09
               ...
tt0109403     4/22/94
tt2364975     3/28/13
tt0116908    10/11/96
tt0343135     1/16/04
tt1600195     9/22/11
Name: release_date, Length: 3000, dtype: object

In [61]:
from datetime import datetime
from datetime import date

* strptime means string parser, this will convert a string format to datetime.
* strftime means string formatter, this will format a datetime object to string format.

In [62]:
df['release_date'][0:5]

imdb_id
tt2637294     2/20/15
tt0368933      8/6/04
tt2582802    10/10/14
tt1821480      3/9/12
tt1380152      2/5/09
Name: release_date, dtype: object

In [71]:
df["new_release_date"] = df["release_date"].apply(lambda x : datetime.strptime(x, "%m/%d/%y"))

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3000 entries, tt2637294 to tt1600195
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  604 non-null    object
 1   budget                 3000 non-null   int64
 2   genres                 2993 non-null   object
 3   homepage               946 non-null    object
 4   original_language      3000 non-null   object
 5   original_title         3000 non-null   object
 6   overview               2992 non-null   object
 7   popularity             3000 non-null   float64
 8   production_companies   2844 non-null   object
 9   production_countries   2945 non-null   object
 10  release_date           3000 non-null   object
 11  runtime                2998 non-null   float64
 12  spoken_languages       2980 non-null   object
 13  status                 3000 non-null   object
 14  tagline                2403 non-null   object
 15  title                  3000 non-null   object
 16  Keywords               2724 non-null   object
 17  cast                   2987 non-null   object
 18  crew                   2984 non-null   object
 19  revenue                3000 non-null   int64
 20  movie_profit           3000 non-null   int64
 21  capitalized_title      3000 non-null   object
 22  new_profit             3000 non-null   int64
 23  new_release_date       3000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(4), object(17)
memory usage: 650.5+ KB

In [73]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,tagline,title,Keywords,cast,crew,revenue,movie_profit,capitalized_title,new_profit,new_release_date
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,HOT TUB TIME MACHINE 2,-1685349,2015-02-20
tt0368933,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",...,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,55149435,2004-08-06
tt2582802,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,WHIPLASH,9792000,2014-10-10
tt1821480,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,"[{'iso_3166_1': 'IN', 'name': 'India'}]",...,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,KAHAANI,14800000,2012-03-09
tt1380152,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,NaN,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",...,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,MARINE BOY,3923970,2009-02-05

In [74]:
df['new_release_date'][0]

<ipython-input-74-007681be0d59>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['new_release_date'][0]

Timestamp('2015-02-20 00:00:00')

In [77]:
# month year and date
print(df["new_release_date"][0].month)
print(df["new_release_date"][0].year)
print(df["new_release_date"][0].day)
print(df["new_release_date"][0].hour)
print(df["new_release_date"][0].minute)
print(df["new_release_date"][0].second)

2
2015
20
0
0
0

<ipython-input-77-15ddeb870fed>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df["new_release_date"][0].month)
<ipython-input-77-15ddeb870fed>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df["new_release_date"][0].year)
<ipython-input-77-15ddeb870fed>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df["new_release_date"][0].day)
<ipython-input-77-15ddeb870fed>:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df["new_release_date"][0].hour)
<ipython-input-77-15ddeb870fed>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df["new_release_date"][0].minute)
<ipython-input-77-15ddeb870fed>:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df["new_release_date"][0].second)

In [78]:
print(date.today())

2024-12-14

In [79]:
print(datetime.now())

2024-12-14 04:36:34.328770

**Let's explore the unique and missing values**

* unique()
* nunique()
* value_counts()
* isnull()
* fillna()

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3000 entries, tt2637294 to tt1600195
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  604 non-null    object
 1   budget                 3000 non-null   int64
 2   genres                 2993 non-null   object
 3   homepage               946 non-null    object
 4   original_language      3000 non-null   object
 5   original_title         3000 non-null   object
 6   overview               2992 non-null   object
 7   popularity             3000 non-null   float64
 8   production_companies   2844 non-null   object
 9   production_countries   2945 non-null   object
 10  release_date           3000 non-null   object
 11  runtime                2998 non-null   float64
 12  spoken_languages       2980 non-null   object
 13  status                 3000 non-null   object
 14  tagline                2403 non-null   object
 15  title                  3000 non-null   object
 16  Keywords               2724 non-null   object
 17  cast                   2987 non-null   object
 18  crew                   2984 non-null   object
 19  revenue                3000 non-null   int64
 20  movie_profit           3000 non-null   int64
 21  capitalized_title      3000 non-null   object
 22  new_profit             3000 non-null   int64
 23  new_release_date       3000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(4), object(17)
memory usage: 650.5+ KB

In [81]:
# find unique values in a column
list(df['status'].unique())

['Released', 'Rumored']

In [82]:
df['status']

imdb_id
tt2637294    Released
tt0368933    Released
tt2582802    Released
tt1821480    Released
tt1380152    Released
               ...
tt0109403    Released
tt2364975    Released
tt0116908    Released
tt0343135    Released
tt1600195    Released
Name: status, Length: 3000, dtype: object

In [83]:
# 3000 values : 100 missing 2900 non null : 100 values i need to fill them  , what can he the most appropriate way to fill this values ! list , 600 , 100!

In [85]:
list(df["original_language"].unique())

['en',
 'hi',
 'ko',
 'sr',
 'fr',
 'it',
 'nl',
 'zh',
 'es',
 'cs',
 'ta',
 'cn',
 'ru',
 'tr',
 'ja',
 'fa',
 'sv',
 'de',
 'te',
 'pt',
 'mr',
 'da',
 'fi',
 'el',
 'ur',
 'he',
 'no',
 'ar',
 'nb',
 'ro',
 'vi',
 'pl',
 'hu',
 'ml',
 'bn',
 'id']

In [86]:
# Counts the number of unique values in a column
df.original_language.nunique()

36

In [87]:
df["original_language"].value_counts() # is all about the predic 100%

original_language
en    2575
fr      78
ru      47
es      43
hi      42
ja      37
it      24
cn      20
ko      20
zh      19
de      18
ta      16
sv       8
nl       6
pt       6
fa       5
da       5
ro       4
hu       3
tr       3
no       2
ml       2
pl       2
te       2
fi       2
ur       1
he       1
el       1
ar       1
nb       1
vi       1
mr       1
cs       1
sr       1
bn       1
id       1
Name: count, dtype: int64

In [88]:
df["runtime"].value_counts()

runtime
90.0     100
100.0     99
105.0     91
95.0      89
98.0      85
        ...
220.0      1
60.0       1
53.0       1
185.0      1
182.0      1
Name: count, Length: 139, dtype: int64

In [89]:
df["homepage"].value_counts()

homepage
http://www.transformersmovie.com/               4
http://www.thehobbit.com/                       2
http://www.lordoftherings.net/                  2
http://sonyclassics.com/whiplash/               1
https://www.facebook.com/thefinesthoursmovie    1
                                               ..
http://admiralfilm.ru/                          1
http://www.jackreachermovie.com/                1
http://www.sleepdealer.com/                     1
http://www.popperspenguins.com/main.html        1
http://www.abductionthefilm.com/                1
Name: count, Length: 941, dtype: int64

In [94]:
df["homepage"].isnull().sum()

0

In [91]:
# Lets fill the missing values with the value -999
df['homepage'].fillna('Not Present',inplace = True)

<ipython-input-91-21d792dee427>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['homepage'].fillna('Not Present',inplace = True)

In [92]:
df.fillna({"homepage": "Not Present"}, inplace=True)

In [93]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,tagline,title,Keywords,cast,crew,revenue,movie_profit,capitalized_title,new_profit,new_release_date
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",Not Present,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,HOT TUB TIME MACHINE 2,-1685349,2015-02-20
tt0368933,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Not Present,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",...,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,55149435,2004-08-06
tt2582802,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,WHIPLASH,9792000,2014-10-10
tt1821480,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,"[{'iso_3166_1': 'IN', 'name': 'India'}]",...,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,KAHAANI,14800000,2012-03-09
tt1380152,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Not Present,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,NaN,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",...,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,MARINE BOY,3923970,2009-02-05

In [96]:
df["revenue"]

imdb_id
tt2637294     12314651
tt0368933     95149435
tt2582802     13092000
tt1821480     16000000
tt1380152      3923970
               ...
tt0109403      1596687
tt2364975       180590
tt0116908     89456761
tt0343135    171963386
tt1600195     82087155
Name: revenue, Length: 3000, dtype: int64

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3000 entries, tt2637294 to tt1600195
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  604 non-null    object
 1   budget                 3000 non-null   int64
 2   genres                 2993 non-null   object
 3   homepage               3000 non-null   object
 4   original_language      3000 non-null   object
 5   original_title         3000 non-null   object
 6   overview               2992 non-null   object
 7   popularity             3000 non-null   float64
 8   production_companies   2844 non-null   object
 9   production_countries   2945 non-null   object
 10  release_date           3000 non-null   object
 11  runtime                2998 non-null   float64
 12  spoken_languages       2980 non-null   object
 13  status                 3000 non-null   object
 14  tagline                2403 non-null   object
 15  title                  3000 non-null   object
 16  Keywords               2724 non-null   object
 17  cast                   2987 non-null   object
 18  crew                   2984 non-null   object
 19  revenue                3000 non-null   int64
 20  movie_profit           3000 non-null   int64
 21  capitalized_title      3000 non-null   object
 22  new_profit             3000 non-null   int64
 23  new_release_date       3000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(4), object(17)
memory usage: 650.5+ KB

In [102]:
df["genres"].isnull().sum()

0

In [101]:
df.dropna(subset = ["genres"],inplace=True)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2993 entries, tt2637294 to tt1600195
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  604 non-null    object
 1   budget                 2993 non-null   int64
 2   genres                 2993 non-null   object
 3   homepage               2993 non-null   object
 4   original_language      2993 non-null   object
 5   original_title         2993 non-null   object
 6   overview               2985 non-null   object
 7   popularity             2993 non-null   float64
 8   production_companies   2844 non-null   object
 9   production_countries   2941 non-null   object
 10  release_date           2993 non-null   object
 11  runtime                2991 non-null   float64
 12  spoken_languages       2976 non-null   object
 13  status                 2993 non-null   object
 14  tagline                2402 non-null   object
 15  title                  2993 non-null   object
 16  Keywords               2722 non-null   object
 17  cast                   2980 non-null   object
 18  crew                   2978 non-null   object
 19  revenue                2993 non-null   int64
 20  movie_profit           2993 non-null   int64
 21  capitalized_title      2993 non-null   object
 22  new_profit             2993 non-null   int64
 23  new_release_date       2993 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(4), object(17)
memory usage: 649.1+ KB

In [105]:
# how to handle the outliers

df.describe()

,budget,popularity,runtime,revenue,movie_profit,new_profit,new_release_date
count,2.993000e+03,2993.000000,2991.000000,2.993000e+03,2.993000e+03,2.993000e+03,2993
mean,2.258209e+07,8.482164,107.851555,6.687931e+07,4.429722e+07,4.429722e+07,2005-02-06 23:06:35.723354624
min,0.000000e+00,0.000001,0.000000,1.000000e+00,-1.074474e+08,-1.074474e+08,1969-01-01 00:00:00
25%,0.000000e+00,4.071187,94.000000,2.405420e+06,2.066600e+04,2.066600e+04,1995-10-27 00:00:00
50%,8.000000e+06,7.392294,104.000000,1.692814e+07,6.166819e+06,6.166819e+06,2006-01-23 00:00:00
75%,2.900000e+07,10.896238,118.000000,6.905570e+07,4.183723e+07,4.183723e+07,2012-09-09 00:00:00
max,3.800000e+08,294.337037,338.000000,1.519558e+09,1.316249e+09,1.316249e+09,2068-11-06 00:00:00
std,3.705444e+07,12.111833,22.085756,1.376564e+08,1.124387e+08,1.124387e+08,NaN

In [108]:
df.drop(columns = ["new_release_date"], inplace=True)

In [109]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,status,tagline,title,Keywords,cast,crew,revenue,movie_profit,capitalized_title,new_profit
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",Not Present,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,HOT TUB TIME MACHINE 2,-1685349
tt0368933,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Not Present,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,55149435
tt2582802,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,WHIPLASH,9792000
tt1821480,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,"[{'iso_3166_1': 'IN', 'name': 'India'}]",...,Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,KAHAANI,14800000
tt1380152,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Not Present,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,NaN,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",...,Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,MARINE BOY,3923970