<a href="https://colab.research.google.com/github/yellaabhiram/Datascience---Python/blob/main/pandas_project_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/excelIMBD.csv')
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [4]:
df.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [9]:
df.loc[~df["Revenue (Millions)"].isna(),'Revenue (Millions)']

0      333.13
1      126.46
2      138.12
3      270.32
4      325.02
        ...
993     60.13
994     54.72
996     17.54
997     58.01
999     19.64
Name: Revenue (Millions), Length: 872, dtype: float64

In [10]:
type(df.loc[0,"Revenue (Millions)"])

numpy.float64

In [11]:
def convert_to_list(str):
  return eval(str)

In [12]:
df_new = df.copy() # making sure we have backup of orginial dataset

In [16]:
df.loc[df["Actors"].isna(),'Actors'].apply(convert_to_list)

Series([], Name: Actors, dtype: object)

In [20]:
df["Actors"][0]

'Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana'

In [21]:
df_new['Actors'][0]

'Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana'

In [23]:
df.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [24]:
df["profit"] = df['Revenue (Millions)']/100000

In [25]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,profit
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,0.003331
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,0.001265
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,0.001381
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,0.002703
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,0.003250

In [50]:
Actors_Highest_rev = df.loc[df['profit'].idxmax(),['Actors','Revenue (Millions)']] #Actors part of highest revenue

In [29]:
df.loc[df['profit'].idxmin(),['Actors','Revenue (Millions)']] ##Actors part of Lowest revenue

Actors                Patrick Wilson, Jessica Biel, Haley Bennett, V...
Revenue (Millions)                                                  0.0
Name: 231, dtype: object

In [38]:
Actors_Highest_rev['Actors'][0:30]

'Daisy Ridley, John Boyega, Osc'

In [57]:
Actors_list = Actors_Highest_rev["Actors"][:]
Actors_list = Actors_list.split( ',  ')
Actors_list

['Daisy Ridley, John Boyega, Oscar Isaac, Domhnall Gleeson']

***Example***

In [ ]:
# producer_list = []
# director_list = []

# for elem in crew_list:
#   if elem["job"] == "Producer":
#     producer_list.append(elem["name"])
#   if elem["job"] == "Director":
#     director_list.append(elem["name"])
#above code can be used when we have dictionary values like below
# [{'credit_id': '52fe4cc8c3a36847f823e681',
#   'department': 'Production',
#   'gender': 2,
#   'id': 12835,
#   'job': 'Producer',
#   'name': 'Vin Diesel',
#   'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
#  {'credit_id': '52fe4cc8c3a36847f823e687',
#   'department': 'Production',
#   'gender': 2,
#   'id': 11874,
#   'job': 'Producer',
#   'name': 'Neal H. Moritz',
#   'profile_path': '/cNcsEYmoS4niCz3UkVAA09dUIob.jpg'},
#  {'credit_id': '52fe4cc8c3a36847f823e68d',
#   'department': 'Writing',
#   'gender': 2,
#   'id': 58191,
#   'job': 'Writer',
#   'name': 'Chris Morgan',
#   'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'}]

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
 12  profit              872 non-null    float64
dtypes: float64(4), int64(4), object(5)
memory usage: 101.7+ KB

In [64]:
Metascore_without_null = df.loc[~df["Metascore"].isna(),'Metascore']
Metascore_without_null

0      76.0
1      65.0
2      62.0
3      59.0
4      40.0
       ...
995    45.0
996    46.0
997    50.0
998    22.0
999    11.0
Name: Metascore, Length: 936, dtype: float64

In [65]:
len(Metascore_without_null)

936

***Example***

In [ ]:
# genres_list = []
# for index,row in genres_without_nullvalues.iterrows():
#   generes = genres_without_nullvalues.loc[index,"genres"]
#   for k in generes:
#     genres_list.append(k["name"])

# pd.DataFrame(set(genres_list),columns=["Unique_Genres"])

# WE CAN USE ABOVE CODE TO GET THE NAME OF GENRES

# DATA
# [{'id': 16, 'name': 'Animation'},
#  {'id': 12, 'name': 'Adventure'},
#  {'id': 10751, 'name': 'Family'}]

In [76]:
df['Actors']

0      Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
1      Noomi Rapace, Logan Marshall-Green, Michael Fa...
2      James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
3      Matthew McConaughey,Reese Witherspoon, Seth Ma...
4      Will Smith, Jared Leto, Margot Robbie, Viola D...
                             ...
995    Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...
996    Lauren German, Heather Matarazzo, Bijou Philli...
997    Robert Hoffman, Briana Evigan, Cassie Ventura,...
998    Adam Pally, T.J. Miller, Thomas Middleditch,Sh...
999    Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...
Name: Actors, Length: 1000, dtype: object

In [81]:

All_actors_list = []
actors_check = df['Actors'][0:50]
for Actors in df['Actors'][0:50]:
  Actors = Actors.split(', ')
  for actor in Actors:
    All_actors_list.append(actor)
All_actors_list

['Chris Pratt',
 'Vin Diesel',
 'Bradley Cooper',
 'Zoe Saldana',
 'Noomi Rapace',
 'Logan Marshall-Green',
 'Michael Fassbender',
 'Charlize Theron',
 'James McAvoy',
 'Anya Taylor-Joy',
 'Haley Lu Richardson',
 'Jessica Sula',
 'Matthew McConaughey,Reese Witherspoon',
 'Seth MacFarlane',
 'Scarlett Johansson',
 'Will Smith',
 'Jared Leto',
 'Margot Robbie',
 'Viola Davis',
 'Matt Damon',
 'Tian Jing',
 'Willem Dafoe',
 'Andy Lau',
 'Ryan Gosling',
 'Emma Stone',
 'Rosemarie DeWitt',
 'J.K. Simmons',
 'Essie Davis',
 'Andrea Riseborough',
 'Julian Barratt,Kenneth Branagh',
 'Charlie Hunnam',
 'Robert Pattinson',
 'Sienna Miller',
 'Tom Holland',
 'Jennifer Lawrence',
 'Chris Pratt',
 'Michael Sheen,Laurence Fishburne',
 'Eddie Redmayne',
 'Katherine Waterston',
 'Alison Sudol,Dan Fogler',
 'Taraji P. Henson',
 'Octavia Spencer',
 'Janelle Monáe,Kevin Costner',
 'Felicity Jones',
 'Diego Luna',
 'Alan Tudyk',
 'Donnie Yen',
 "Auli'i Cravalho",
 'Dwayne Johnson',
 'Rachel House',
 'Temuera Morrison',
 'Anne Hathaway',
 'Jason Sudeikis',
 'Austin Stowell,Tim Blake Nelson',
 'Louis C.K.',
 'Eric Stonestreet',
 'Kevin Hart',
 'Lake Bell',
 'Andrew Garfield',
 'Sam Worthington',
 'Luke Bracey,Teresa Palmer',
 'Matt Damon',
 'Tommy Lee Jones',
 'Alicia Vikander,Vincent Cassel',
 'Dev Patel',
 'Nicole Kidman',
 'Rooney Mara',
 'Sunny Pawar',
 'Amy Adams',
 'Jeremy Renner',
 'Forest Whitaker,Michael Stuhlbarg',
 'Matthew McConaughey',
 'Edgar Ramírez',
 'Bryce Dallas Howard',
 'Corey Stoll',
 'Casey Affleck',
 'Michelle Williams',
 'Kyle Chandler,Lucas Hedges',
 'Emma Booth',
 'Ashleigh Cummings',
 'Stephen Curry,Susie Porter',
 'Anna Kendrick',
 'Justin Timberlake,Zooey Deschanel',
 'Christopher Mintz-Plasse',
 'Liam Hemsworth',
 'Jeff Goldblum',
 'Bill Pullman,Maika Monroe',
 'Fiona Gordon',
 'Dominique Abel,Emmanuelle Riva',
 'Pierre Richard',
 'Prabhas',
 'Rana Daggubati',
 'Anushka Shetty,Tamannaah Bhatia',
 'Jocelin Donahue',
 'Jesse Bradford',
 'Jesse Borrego,Lori Petty',
 'Mila Kunis',
 'Kathryn Hahn',
 'Kristen Bell,Christina Applegate',
 'Michael Fassbender',
 'Marion Cotillard',
 'Jeremy Irons,Brendan Gleeson',
 'Zoey Deutch',
 'James Franco',
 'Tangie Ambrose,Cedric the Entertainer',
 'Amy Adams',
 'Jake Gyllenhaal',
 'Michael Shannon',
 'Aaron Taylor-Johnson',
 'James McAvoy',
 'Michael Fassbender',
 'Jennifer Lawrence',
 'Nicholas Hoult',
 'Ryan Reynolds',
 'Morena Baccarin',
 'T.J. Miller',
 'Ed Skrein',
 'Milla Jovovich',
 'Iain Glen',
 'Ali Larter',
 'Shawn Roberts',
 'Chris Evans',
 'Robert Downey Jr.,Scarlett Johansson',
 'Sebastian Stan',
 'Matthew McConaughey',
 'Anne Hathaway',
 'Jessica Chastain',
 'Mackenzie Foy',
 'Benedict Cumberbatch',
 'Chiwetel Ejiofor',
 'Rachel McAdams',
 'Benedict Wong',
 'Denzel Washington',
 'Chris Pratt',
 "Ethan Hawke,Vincent D'Onofrio",
 'John Francis Daley',
 'Austin Pendleton',
 'Colleen Camp',
 'Neil Flynn',
 'Seth Rogen',
 'Kristen Wiig',
 'Jonah Hill',
 'Alistair Abell',
 'Mahershala Ali',
 'Shariff Earp',
 'Duan Sanderson',
 'Alex R. Hibbert',
 'Brittany Blanton',
 'Ayse Howard',
 'Roman Jossart,Nadia White',
 'Michael Keaton',
 'Nick Offerman',
 'John Carroll Lynch',
 'Linda Cardellini',
 'Gabriel Chavarria',
 'Demián Bichir',
 'Theo Rossi,Tony Revolori',
 'Johnny Depp',
 'Penélope Cruz',
 'Ian McShane',
 'Geoffrey Rush',
 'Jessica Chastain',
 'Mark Strong',
 'Gugu Mbatha-Raw,Michael Stuhlbarg',
 'Hermione Corfield',
 'Addison Timlin',
 'Joely Richardson,Jeremy Irvine',
 'Chris Pine',
 'Zachary Quinto',
 'Karl Urban',
 'Zoe Saldana',
 'Charlize Theron',
 'Javier Bardem',
 'Adèle Exarchopoulos,Jared Harris']

In [94]:
# All_actors_list.value_counts()
from collections import Counter
actors_counts = Counter(All_actors_list)
actors_counts

for actor,count in actors_counts.items():
  if count > 1:
    All_count = (f"{actor} :  {count} ")
    print(All_count)

Chris Pratt :  3
Zoe Saldana :  2
Michael Fassbender :  3
Charlize Theron :  2
James McAvoy :  2
Matt Damon :  2
Jennifer Lawrence :  2
Anne Hathaway :  2
Amy Adams :  2
Matthew McConaughey :  2
Jessica Chastain :  2